project_id = "cuotwiqzazkrwiuxacfw"

[functions.create-checkout]
verify_jwt = false

[functions.get-stripe-price]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.seed-test-users]
verify_jwt = false